name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  camera: ^0.11.0+2
  provider: ^6.0.5
  flutter_secure_storage: ^9.2.4
  intl: ^0.18.1
  http: ^1.1.0
  supabase_flutter: ^2.0.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
